function opt = initRnnOpt(action)
%initilize options in trainLSTM_SMAP.lua and testLSTM_SMAP.lua.
% input
% action - 1 for train, 2 for test

% output
% opt - a structure contains LSTM default options following LSTM codes.

% example

if action ==1
    opt=struct(...
        'gpu',1,...
        'out','test',...
        'train','CONUSv4f1',...
        'var','varLst_Noah',...
        'varC','varConstLst_Noah',...
        'resume',0,...
        'rootDB','',...
        'rootOut','',...
        'hiddenSize',256,...
        'rho',30,...
        'rhoP',0,...
        'dr',0.5,...
        'nbatch',100,...
        'nEpoch',[],...
        'saveEpoch',500,...
        'timeOpt',1,...
        'target','SMAP',...
        'syr',2015,...
        'eyr',2015,...
        'addFlag',0);
elseif action==2
    opt=struct(...
        'gpu',1,...
        'out','test',...
        'test','CONUSv4f1',...
        'epoch',500,...
        'rootDB','',...
        'rootOut','',...
        'timeOpt',2,...
        'drMode',0,...
        'syr',2015,...
        'eyr',2015);
else
    error('wrong action. plz input 1 or 2')
end
end

