%% plot box
global kPath
rootDB=kPath.DBSMAP_L3_NA;
rootOut=kPath.OutSMAP_L3_NA;
trainName='CONUSv4f1';
testName='CONUSv4f1';
epoch=500;

outNameLst = {'CONUSv4f1_2015',...
%     'CONUSv4f1_tied_relu_drXHC',...
%     'CONUSv4f1_tied_relu_drXH',...
%     'CONUSv4f1_tied_relu_drC',...
%     'CONUSv4f1_tied_relu_drW',...
%     'CONUSv4f1_untied_relu_drXHC',...
%     'CONUSv4f1_untied_relu_drXH',...
%     'CONUSv4f1_untied_relu_drC',...
%     'CONUSv4f1_untied_relu_drW',...
%     'CONUSv4f1_tied_drHC',...
%     'CONUSv4f1_tied_drH',...
%     'CONUSv4f1_tied_drC',...
%     'CONUSv4f1_tied_drW',...
%     'CONUSv4f1_untied_drHC',...
%     'CONUSv4f1_untied_drH',...
%     'CONUSv4f1_untied_drC',...
%     'CONUSv4f1_untied_drW',...
    'cudnn_local3'    
    };
xNameLst={'ref',...
%     'tied-relu-drXHC',...
%     'tied-relu-drXH',...
%     'tied-relu-drC',...
%     'tied-relu-drW',...
%     'untied-relu-drXHC',...
%     'untied-relu-drXH',...
%     'untied-relu-drC',...
%     'untied-relu-drW',...
%     'tied-drHC',...
%     'tied-drH',...
%     'tied-drC',...
%     'tied-drW',...
%     'untied-drHC',...
%     'untied-drH',...
%     'untied-drC',...
%     'untied-drW',...
    'cudnn'
    };
statMat={};
for k=1:length(outNameLst)
    outName=outNameLst{k};
    out1= postRnnGlobal_load(outName,trainName,[2015,2015],...
        'rootDB',rootDB,'rootOut',rootOut,'readModel',0);
    out2= postRnnGlobal_load(outName,trainName,[2016,2017],...
        'rootDB',rootDB,'rootOut',rootOut,'readModel',0);
    stat1=statCal(out1.yLSTM,out1.ySMAP);
    stat2=statCal(out2.yLSTM,out2.ySMAP);
    statMat{k,1}=stat1.rmse;
    statMat{k,2}=stat2.rmse;
    mean(stat2.rmse)
end

f=plotBoxSMAP(statMat,{'train','test'},xNameLst);
ylim([0,0.08])