treeFolder='E:\Kuai\SSRS\tree\solo\';

for kt=0:0
    for km=0:4
        for c=0:5
            treeMatFile=[treeFolder,'c',num2str(c),'_model',num2str(km),'_tree',num2str(kt),'.mat'];
            plotTreeStampSolo(treeMatFile,c)
        end
    end
end

% %% several trees required by CP
% figlist=[...
%     0,1;...
%     1,0;...
%     1,2;...
%     2,0;...
%     3,0;...
%     4,0;...
%     4,1;...
%     5,0;...
%     5,2;...
%     ];
% 
% for i=1:size(figlist,1)
%     kt=0;
%     km=figlist(i,2);
%     c=figlist(i,1);
%     treeMatFile=[treeFolder,'c',num2str(c),'_model',num2str(km),'_tree',num2str(kt),'.mat'];
%     plotTreeStampSolo(treeMatFile,c)
% end
s